language: go

go:
  - 1.4

before_install:
  - cp .netrc ~
  - chmod 600 .netrc

install:
  - git clone https://github.com/nicholaskh/pushd

script:
  - go test ./... -v

notifications:
  email: false
